'use strict';
const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const os = require('os');
const config = require('./config');

// 强杀 CATIA 主进程（CNEXT.exe）。
// 注意：整套服务必须跑在「专用」登录会话，避免误杀该机器上其他人的 CATIA。
function killCatia() {
  return new Promise((resolve) => {
    const k = spawn('taskkill', ['/IM', 'CNEXT.exe', '/F'], { windowsHide: true });
    k.on('exit', () => resolve());
    k.on('error', () => resolve());
  });
}

function classify(files) {
  const products = files.filter((f) => /\.catproduct$/i.test(f));
  const parts = files.filter((f) => /\.catpart$/i.test(f));
  return { products, parts };
}

// 调用 VBScript 驱动 CATIA 转换（cscript）；带超时看门狗。
//
// 与旧版不同：本版支持「多个根产品」各自导出一个 STEP。驱动会先扫描各产品
// 的引用关系，判定哪些产品是「根（不被其它产品引用）」，再逐个导出。
// 路径策略：CATIA V5 无法打开含非常规 Unicode 字符的路径，所以把所有上传文件
// 先复制到一个干净的 ASCII 临时目录，再从该目录打开产品并导出 STEP。
function runDriver(batchFiles, outDir, timeoutMs, forcedRoots) {
  return new Promise((resolve, reject) => {
    const workDir = fs.mkdtempSync(path.join(os.tmpdir(), 'catia-stp-'));
    let cleaned = false;
    const cleanup = () => {
      if (cleaned) return;
      cleaned = true;
      try { fs.rmSync(workDir, { recursive: true, force: true }); } catch (_) {}
    };

    try {
      fs.mkdirSync(outDir, { recursive: true });
      // 1) 复制整批文件到干净临时目录（扁平），让产品能就近找到零件 / 子产品
      for (const f of batchFiles) {
        fs.copyFileSync(f, path.join(workDir, path.basename(f)));
      }
    } catch (e) {
      cleanup();
      return reject(new Error('复制上传文件到临时目录失败: ' + e.message));
    }

    const files = batchFiles.map((f) => path.basename(f));
    const { products, parts } = classify(files);
    const timeoutSec = Math.floor(timeoutMs / 1000);

    // 三组参数：产品 / 零件 / 强制指定的根（若有）。用 "--" 分段。
    const args = [
      '//nologo', config.driverScript,
      workDir, outDir, String(timeoutSec),
      ...products, '--', ...parts,
    ];
    if (Array.isArray(forcedRoots) && forcedRoots.length) {
      args.push('--', ...forcedRoots);
    }

    const ps = spawn('cscript.exe', args, { windowsHide: false });
    let out = '';
    let err = '';
    ps.stdout.on('data', (d) => { out += d.toString(); });
    ps.stderr.on('data', (d) => { err += d.toString(); });

    const timer = setTimeout(async () => {
      try { ps.kill('SIGKILL'); } catch (_) {}
      await killCatia();
      cleanup();
      reject(new Error(`CATIA 转换超时（>${timeoutSec}s），已强杀进程`));
    }, timeoutMs);

    ps.on('error', (e) => {
      clearTimeout(timer);
      cleanup();
      reject(new Error('无法启动 cscript 驱动: ' + e.message));
    });
    ps.on('exit', async (code) => {
      clearTimeout(timer);
      try {
        if (code !== 0) {
          return reject(new Error(`驱动异常退出(code=${code}): ${err || out || '未知错误'}`));
        }
        const m = out.match(/ROOTS\|([^\r\n]*)/);
        let roots = [];
        if (m) roots = m[1].split('|').map((s) => s.trim()).filter(Boolean);

        const produced = fs.readdirSync(outDir)
          .filter((f) => /\.stp$/i.test(f))
          .map((f) => ({ name: f, base: path.parse(f).name.toLowerCase(), path: path.join(outDir, f) }));

        if (!roots.length && !produced.length) {
          return reject(new Error('驱动退出码 0，但未生成 .stp 文件'));
        }
        // 把每个根产品与其导出的 .stp 配对（按文件名 base 匹配）
        const byBase = {};
        produced.forEach((p) => { byBase[p.base] = p; });
        const steps = roots
          .map((r) => byBase[path.parse(r).name.toLowerCase()] || null)
          .filter(Boolean);

        if (roots.length && steps.length !== roots.length) {
          const missing = roots.filter((r) => !byBase[path.parse(r).name.toLowerCase()]);
          return reject(new Error('部分根产品导出失败（未生成对应 .stp）: ' + missing.join(', ')));
        }
        resolve({ roots, steps });
      } catch (e) {
        reject(new Error('转换后处理失败: ' + (e && e.message)));
      } finally {
        cleanup();
      }
    });
  });
}

// MOCK：无 CATIA 时生成占位 STEP。多根策略的占位实现：
// - 有强制根（手动改选）→ 只导出这些
// - 否则有产品 → 每个产品各导出一个 STEP（真实模式会剔除被嵌套的子产品，MOCK 无法判定，保守全部导出）
// - 无产品 → 每个零件各导出一个 STEP
// 用于在无 CATIA 的机器上验证整条队列/状态/下载链路。
function runMock(batchFiles, outDir, forcedRoots) {
  const files = batchFiles.map((f) => path.basename(f));
  const { products, parts } = classify(files);
  let targets;
  if (Array.isArray(forcedRoots) && forcedRoots.length) {
    targets = forcedRoots.filter((r) => products.includes(r) || parts.includes(r));
  } else {
    targets = products.length ? products : parts;
  }
  fs.mkdirSync(outDir, { recursive: true });
  const steps = targets.map((t) => {
    const p = path.join(outDir, path.parse(t).name + '.stp');
    const content =
      `ISO-10303-21;\n/* Mock STEP generated by catia-stp-converter (MOCK mode) */\n` +
      `/* source: ${t} */\n` +
      `/* batch: ${files.join(', ')} */\n` +
      `END-ISO-10303-21;\n`;
    fs.writeFileSync(p, content);
    return { name: t, path: p };
  });
  const roots = targets; // MOCK 无法扫描引用；强制模式下根 = 所选；否则 = 全部产品/零件
  return Promise.resolve({ roots, steps });
}

// batchFiles: 原始文件路径数组
// outDir: 结果输出目录（.stp 直接落在此处）
// timeoutMs: 超时（毫秒）
// forcedRoots: 可选，强制只导出这些产品（手动改选时传入）
function convert(batch, outDir, timeoutMs, forcedRoots) {
  if (config.mock) return runMock(batch, outDir, forcedRoots);
  return runDriver(batch, outDir, timeoutMs, forcedRoots);
}

module.exports = { convert, killCatia };
